-- 코드를 입력하세요
SELECT P.PRODUCT_CODE AS PRODUCT_CODE,(P.PRICE*O.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P JOIN (SELECT PRODUCT_ID,SUM(SALES_AMOUNT) AS SALES_AMOUNT
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID)
                    AS O ON P.PRODUCT_ID=O.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC;




# SELECT PRODUCT_ID,SUM(SALES_AMOUNT) AS SALES_AMOUNT
# FROM OFFLINE_SALE
# GROUP BY PRODUCT_ID
# ORDER BY PRODUCT_ID