-- 코드를 입력하세요
SELECT O.ANIMAL_ID AS ANIMAL_ID,O.NAME AS NAME
FROM ANIMAL_OUTS AS O LEFT JOIN ANIMAL_INS AS I
        ON O.ANIMAL_ID=I.ANIMAL_ID
WHERE I.NAME IS NULL && O.NAME IS NOT NULL
ORDER BY ANIMAL_ID,NAME;