-- 코드를 입력하세요
SELECT MEMBER.MEMBER_NAME AS MEMBER_NAME, REVIEW.REVIEW_TEXT AS REVIEW_TEXT,DATE_FORMAT(REVIEW.REVIEW_DATE,'%Y-%m-%d')AS REVIEW_DATE
FROM REST_REVIEW AS REVIEW JOIN (SELECT F.MEMBER_ID,F.MEMBER_NAME,R.COUNT_REVIEW
                        FROM MEMBER_PROFILE AS F JOIN (SELECT COUNT(REVIEW_ID) AS COUNT_REVIEW,MEMBER_ID
                                    FROM REST_REVIEW
                                    GROUP BY MEMBER_ID) AS R
                            ON F.MEMBER_ID=R.MEMBER_ID
                    ORDER BY R.COUNT_REVIEW DESC
                    LIMIT 1) AS MEMBER
        ON REVIEW.MEMBER_ID=MEMBER.MEMBER_ID
ORDER BY REVIEW_DATE ASC,REVIEW_TEXT ASC;

